# 普通数据的配置
name: zhangsan

# 对象的配置
person:
  name: zhangsan
  age: 18
  addr: beijing

# 行内对象配置(类json)
server: {port: 8082}

# 配置数组、集合(普通字符串)
city:
  - beijing
  - tianjin

# 或city: [beijing,tianjin]

# 配置数组、集合(对象数据)
student:
  - name: tom
    age: 18
    addr: beijing
  - name: lucy
    age: 17
    addr: tianjin

# 或student: [{name: tom,age: 18,addr: beijing},{name: lucy,age: 17,addr: tianjin}]

# Map配置
map:
  key1: value1
  key2: value2